### ISSUE TITLE
JEI stacktrace on trying to log in to the server. at co.q64.stars.link.jei.StarsJEIPlugin.registerRecipes(StarsJEIPlugin.java:45)

### ISSUE THREAD

**Issue by ProsperCraft** [Quantum64/Stars#3]
I am trying to log in to my server and I am unable to and I am watching the logs and see this stacktrace-

https://gist.github.com/ProsperCraft/e91552d074c165e442f9acfdd8aa8e33

Although this is prolly not the reason, I thought you might want to see if it there can be something done about it.

**Comment by Quantum64** [comment]
Unrelated to stars
